name: Publish npm package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Publish package to GitHub Package Registry
        run: echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }} > .npmrc && npm publish --registry=https://npm.pkg.github.com
      
      - name: Publish package to NPM
        run: echo //registry.npmjs.org/:_authToken=${{ secrets.NPM_BOTTY_TOKEN }} > .npmrc && npm publish --registry=https://registry.npmjs.org
